name: Bug report
description: Create a report to help us improve
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure to provide as much context as you can in order to help us triage and track down your bug as quickly as possible.

        Before filing a bug, please search through [existing issues](https://github.com/open-telemetry/opentelemetry-swift/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) to see if an existing issue covers your bug.
  - type: textarea
    attributes:
      label: What happened?
      description: Please provide as much detail as you reasonably can.
      value: |
        ## Description

        ## Steps to Reproduce

        ## Expected Result

        ## Actual Result

    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of OpenTelemetry Swift did you use?
      placeholder: "e.g., 1.5.0"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Swift Version
      description: What version of Swift are you using?
      options:
        - "5.9"
        - "5.10"
        - "5.11"
        - "Other (please specify in additional context)"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Platform
      description: Which platform(s) are you targeting?
      multiple: true
      options:
        - "iOS"
        - "macOS"
        - "watchOS"
        - "tvOS"
        - "Linux"
        - "Other (please specify in additional context)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment information
      description: Please provide any additional information about your environment.
      value: |
        - Xcode version: (if applicable)
        - iOS version: (if applicable)
        - macOS version: (if applicable)
        - Package manager: (SPM, CocoaPods, etc.)
  - type: textarea
    attributes:
      label: Code sample
      description: |
        Please provide a minimal code sample that reproduces the issue.
      render: swift
  - type: textarea
    attributes:
      label: Log output
      description: |
        Please copy and paste any relevant log output, stack traces, or error messages.
      render: shell
  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this issue.
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0