name: General issue
description: Report any other issue or ask a question
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please provide as much context as you can to help us understand your situation.

        Before filing an issue, please search through [existing issues](https://github.com/open-telemetry/opentelemetry-swift/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) to see if a similar issue already exists.
  - type: dropdown
    attributes:
      label: Type of issue
      description: What type of issue are you reporting?
      options:
        - "Question"
        - "Documentation issue"
        - "Performance issue"
        - "Build/compilation issue"
        - "Installation issue"
        - "Other"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Please provide a clear and detailed description of the issue or question.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of OpenTelemetry Swift are you using?
      placeholder: "e.g., 1.5.0"
  - type: dropdown
    attributes:
      label: Platform
      description: Which platform(s) are you using?
      multiple: true
      options:
        - "iOS"
        - "macOS"
        - "watchOS"
        - "tvOS"
        - "Linux"
        - "Other (please specify in additional context)"
  - type: textarea
    attributes:
      label: Environment information
      description: Please provide any additional information about your environment.
      value: |
        - Xcode version: (if applicable)
        - Swift version: 
        - Package manager: (SPM, CocoaPods, etc.)
  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this issue.
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0